### ISSUE TITLE
Exposed Account Information

### ISSUE THREAD

**Issue by ashley-crux** [Zangorth/AITA#1]
Careful, man. Now I know you like little anime schoolgirls and needed a room-mate last year.

https://github.com/Zangorth/AITA/blob/73005b28e55455c778581670bd1767a32d751eea/Data%20Collection.py#L8-L9

[Remove the sensitive data from your repository and its history](https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository). Also, change your Reddit password.

**Comment by Zangorth** [comment]
Thanks for the heads up, I didn't know anyone actually looked at my Github.
